'pr::package':
  - changed-files:
      - any-glob-to-any-file: ['Cargo.lock', 'Cargo.toml']

'pr::docs':
  - changed-files:
      - any-glob-to-any-file: '**.md'

'pr::code':
  - changed-files:
      - any-glob-to-any-file: ['src/**/*.rs']

'pr::colors':
  - changed-files:
      - any-glob-to-any-file: ['src/colors.rs']

'pr::core':
  - changed-files:
      - any-glob-to-any-file: ['src/lib.rs', 'src/printer.rs']

'pr::github':
  - changed-files:
      - any-glob-to-any-file: '.github/**'

'pr::infra':
  - changed-files:
      - any-glob-to-any-file: '.github/**'

'pr::feature':
  - head-branch: ['feature', 'feat', 'enhancement', 'add']

'pr::patch':
  - head-branch: ['update', 'edit']

'pr::fix':
  - head-branch: ['fix', 'bug']
